### ISSUE TITLE
Error with tuple of results when running eof

### ISSUE THREAD

**Issue by julialiu18** [scottstanie/sentineleof#17]
File "/Users/jukesliu/opt/anaconda3/lib/python3.8/site-packages/eof/download.py", line 122, in download_eofs
    item['path'] for item in result.downloaded.values()
AttributeError: 'tuple' object has no attribute 'downloaded'

**Comment by scottstanie** [comment]
Hi @julialiu18 , sorry about that error. I believe this is from having the older, pre-1.0 version of the `sentinelsat` package.

In that version, `download_all` returns a tuple,
https://github.com/sentinelsat/sentinelsat/blob/v0.14/sentinelsat/sentinel.py#L809

But starting in 1.0 it returns a `NamedTuple`: 
https://github.com/sentinelsat/sentinelsat/blob/main/sentinelsat/sentinel.py#L812

I wish I knew a way to have the dependency upgrade automatically when you get the new version of a pip package, but I dont think that works with `pip`.

If you do

`pip install --upgrade sentinelsat` (or equivalently upgrade with conda), it should fix this problem.

**Comment by julialiu18** [comment]
That fixed it! Thank you.
