### ISSUE TITLE
minimum python version (3.6, 3.5, or 2.7)

### ISSUE THREAD

**Issue by scottstanie** [scottstanie/sentineleof#27]
After @avalentino added testing github action, I removed the python 3.6+ specific code in this repo, but `sentinelsat` has dropped support for python 3.5. 

There only seem to be a few 3.5 downloads
https://pypistats.org/packages/sentineleof

and none in the last month

```
$ pypistats python_minor sentineleof --last-month
| category | percent | downloads |
|:---------|--------:|----------:|
| 3.7      |  30.24% |        62 |
| 3.8      |  25.85% |        53 |
| null     |  22.93% |        47 |
| 3.6      |  16.59% |        34 |
| 3.9      |   2.44% |         5 |
| 2.7      |   1.46% |         3 |
| 3.10     |   0.49% |         1 |
| Total    |         |       205 |
```

so I think the options are...

1. require 3.6, like sentinelsat, and change nothing else
2. allow 3.5, and perform the scihub queries without the `sentinelsat` like they do with hyp3 https://github.com/ASFHyP3/hyp3-lib/blob/develop/hyp3lib/get_orb.py#L59-L81
3. go back and also allow python2.7. Only adding this here because the last tool I made for some folks at JPL got requests to not exclude 2.7

**Comment by avalentino** [comment]
Personally I would go with option 1

**Comment by scottstanie** [comment]
alright that seems like the best one for now, and i'll reconsider if I get specific requests from people
