### ISSUE TITLE
Error-1

### ISSUE THREAD

**Issue by mdavid3** [scottstanie/sentineleof#30]
I install with pip install sentineleof and then when eof runs I get the following error. 
I am using ubuntu 18.04. 

Traceback (most recent call last):
  File "/home/david/.local/bin/eof", line 7, in <module>
    from eof.cli import cli
  File "/home/david/.local/lib/python2.7/site-packages/eof/__init__.py", line 1, in <module>
    from . import download
  File "/home/david/.local/lib/python2.7/site-packages/eof/download.py", line 31, in <module>
    from .scihubclient import ASFClient, ScihubGnssClient
  File "/home/david/.local/lib/python2.7/site-packages/eof/scihubclient.py", line 24
    t0: datetime.datetime, t1: datetime.datetime, data: Sequence[SentinelOrbit]
      ^
SyntaxError: invalid syntax

**Comment by scottstanie** [comment]
Hi David, it looks like you're using Python 2.7. At some point, we started
using features that are only in python 3, since python 2 is no longer
officially supported.


You could try uninstalling with pip, then do

python3 -m pip install sentineleof


Which will make sure to install it using the python 3 version

**Comment by mdavid3** [comment]
thank you so much,
The final question ;

![111](https://user-images.githubusercontent.com/101168839/159016954-f2486441-d014-4d5e-b4bf-44a53dfc058b.jpg)
![2222](https://user-images.githubusercontent.com/101168839/159016963-2b5848b1-016b-4917-9cd7-f5c908d24254.jpg)

**Comment by scottstanie** [comment]
Yes this is a good question and one that I'm only partially sure of....
I believe when ESA transferred from the old API to the new one, some of the
orbit files were regenerated. I havent taken time to check if the orbit
solutions are actually different, but that first date in the file name
(which is something like "generated on") is newer than the old ones. I
haven't had any problems using the new versions, but let me know if you
notice something.

**Comment by mdavid3** [comment]
Thank you so much.
I will check it.
