### ISSUE TITLE
Slightly wrong orbit file for edge cases

### ISSUE THREAD

**Issue by bbuzz31** [scottstanie/sentineleof#33]
If you run `eof` to grab the orbit file for this slc: `S1A_IW_SLC__1SDV_20230106T235934_20230107T000001_046670_059804_D8E3.zip`

It downloads this file: `S1A_OPER_AUX_POEORB_OPOD_20230127T081807_V20230106T225942_20230108T005942.EOF`

If you look closely, the orbit file starts on 1/6/2023 at 22:59:**42**, which is a bit later than the sensing start of 1/6/2023 at 22:59:**34**. I'm not sure what/if this has an effect downstream but thought it would be worth mentioning.

**Comment by scottstanie** [comment]
That also had me head scratching awhile... but it's actually hour 22 vs hour 23, so the orbit does cover the file. Might be easier to see like this:

```python console

In [1]: from apertools import parsers; from rich import print

In [2]: print(parsers.Sentinel("S1A_IW_SLC__1SDV_20230106T235934_20230107T000001_046670_059804_D8E3.zip"))
Sentinel(
    filename='S1A_IW_SLC__1SDV_20230106T235934_20230107T000001_046670_059804_D8E3.zip',
    start_time=datetime.datetime(2023, 1, 6, 23, 59, 34, tzinfo=datetime.timezone.utc),
    stop_time=datetime.datetime(2023, 1, 7, 0, 0, 1, tzinfo=datetime.timezone.utc),
    relative_orbit=48,
    polarization='DV',
    mission='S1A'
)

In [3]: print(parsers.SentinelOrbit("S1A_OPER_AUX_POEORB_OPOD_20230127T081807_V20230106T225942_20230108T005942.EOF"))
SentinelOrbit(
    filename='S1A_OPER_AUX_POEORB_OPOD_20230127T081807_V20230106T225942_20230108T005942.EOF',
    orbit_type='precise',
    start_time=datetime.datetime(2023, 1, 6, 22, 59, 42, tzinfo=datetime.timezone.utc),
    stop_time=datetime.datetime(2023, 1, 8, 0, 59, 42, tzinfo=datetime.timezone.utc)
)

```

**Comment by bbuzz31** [comment]
@scottstanie sorry about that! Staring at too many orbits files too late in the day 😵‍💫
