### ISSUE TITLE
`query_orbit_by_dt` fails for scenes for which no precision orbit is available

### ISSUE THREAD

**Issue by asjohnston-asf** [scottstanie/sentineleof#39]
See https://github.com/dbekaert/RAiDER/issues/576

`_select_orbit` defined at https://github.com/scottstanie/sentineleof/blob/master/eof/scihubclient.py#L88 has no orbit_type parameter, but it's called with that parameter at https://github.com/scottstanie/sentineleof/blob/master/eof/scihubclient.py#L168 . This results in a `TypeError: ScihubGnssClient._select_orbit() got an unexpected keyword argument 'orbit_type'` exception for scenes for which no precision orbit is available.

**Comment by scottstanie** [comment]
Very sorry about that. I've pushed a fix https://github.com/scottstanie/sentineleof/pull/40

It'll be up on pypi shortly, and i'll bump the conda-forge version once that's in.
