### ISSUE TITLE
No orbit data downloaded

### ISSUE THREAD

**Issue by ditafaith** [scottstanie/sentineleof#45]
Hi, 
I have the S1 data from Jan to Oct 2023 and when T execute the eof command got following message,
_eof.scihubclient.ValidityError: none of the input products completely covers the requested time interval: [t0=2023-10-13 11:15:11, t1=2023-10-13 11:16:11]_
Is it related to the latest images that I downloaded?
if yes, I expect still possible to continue downloading the restitute one.

**Comment by ditafaith** [comment]
> Can you post the actual Sentinel file name that failed?
Here is the filename, however there is no available precise orbit
S1A_IW_SLC__1SDV_20230110T111503_20230110T111533_046720_0599CC_3164

**Comment by ditafaith** [comment]
> Can you post the actual Sentinel file name that failed?

Here is the filename, however there is no available precise orbit
S1A_IW_SLC__1SDV_20230110T111503_20230110T111533_046720_0599CC_3164

**Comment by scottstanie** [comment]
I think it might have been a different one that failed, as that one is from January:
```

In [1]: from eof import products

In [2]: products.Sentinel('S1A_IW_SLC__1SDV_20230110T111503_20230110T111533_046720_0599CC_3164')
Out[2]: Sentinel S1A, path 98 from 2023-01-10

```
But I entered the exact date time `2023-10-13 11:15:11` from your error message, it that works now (whereas before it was failing). Please let me know if it still doesn't work with the latest release

**Comment by ditafaith** [comment]
Sorry for my mistake. The correct one is S1A_IW_SLC__1SDV_20231013T111511_20231013T111541_050745_061D79_65D3.zip
The data should be on 20231013. However, there is encounter an error, which means no orbit was downloaded.
Is it possible to read particular directory and put the orbit data in the desired path ?

**Comment by scottstanie** [comment]
Have you installed the latest version? That file is working for me

```
(mapping) staniewi:sentineleof$ touch S1A_IW_SLC__1SDV_20231013T111511_20231013T111541_050745_061D79_65D3
(mapping) staniewi:sentineleof$ eof
[10/30 22:55:32] [INFO download.py] Downloading precise orbits for S1A on 2023-10-13
[10/30 22:55:33] [INFO download.py] Attempting download from SciHub
Downloading S1A_OPER_AUX_RESORB_OPOD_20231013T133254_V20231013T093852_20231013T125622.EOF: 100%|███████████████████████████| 590k/590k [00:02<00:00, 268kB/s]
Downloading products: 100%|████████████████████████████████████| 1/1 [00:03<00:00,  3.21s/product]
```

**Comment by scottstanie** [comment]
> Is it possible to read particular directory and put the orbit data in the desired path ?
use `--search-path` and `--save-dir`

```
(mapping) staniewi:sentineleof$ eof --search-path in_dir/ --save-dir out_dir/
[10/30 22:58:04] [INFO download.py] Downloading precise orbits for S1A on 2023-10-13
[10/30 22:58:05] [INFO download.py] Attempting download from SciHub
Downloading S1A_OPER_AUX_RESORB_OPOD_20231013T133254_V20231013T093852_20231013T125622.EOF: 100%|██████████████████████████████████████████████████████████████████████████████████| 590k/590k [00:02<00:00, 230kB/s]
Downloading products: 100%
```

```bash
$ eof --help
Usage: eof [OPTIONS]

  Download Sentinel precise orbit files.

  Saves files to `save-dir` (default = current directory)

  Download EOFs for specific date, or searches for Sentinel files in --path.
  Will find both ".SAFE" and ".zip" files matching Sentinel-1 naming
  convention. With no arguments, searches current directory for Sentinel 1
  products

Options:
  -p, --search-path DIRECTORY     Path of interest for finding Sentinel
                                  products.   [default: .]
  --save-dir DIRECTORY            Directory to save output .EOF files into
                                  [default: .]
  --sentinel-file PATH            Specify path to download only 1 .EOF for a
```

**Comment by ditafaith** [comment]
I make sure use the latest version.
Here is the error log as attached.
[log.txt](https://github.com/scottstanie/sentineleof/files/13212089/log.txt)

**Comment by scottstanie** [comment]
Ok just to make sure, what version does it say 0.8.3 for this?

```
$ python -c 'from importlib.metadata import version; print(version("sentineleof"))'
0.8.3
```
