### ISSUE TITLE
 https://qc.sentinel1.eo.esa.int discontinued

### ISSUE THREAD

**Issue by avalentino** [scottstanie/sentineleof#6]
The old S1-QC site has been discontinued.
The alternative service https://qc.sentinel1.copernicus.eu should have the same API but it seems that currently it does not provided orbit files.

The recommended alternative is https://scihub.copernicus.eu/gnss which has a different API and requires authentication.

See also https://github.com/johntruckenbrodt/pyroSAR/pull/130.

**Comment by scottstanie** [comment]
oof, thanks for pointing this out, hadn't seen that it was down.

The QC website you linked seems to also have a link to http://aux.sentinel1.eo.esa.int, which does have recent orbit files (e.g.  http://aux.sentinel1.eo.esa.int/POEORB/2021/03/04/ )
Do you know of any reason not to use this one? I looked at the PyroSAR changes they made and it seemed like a good chunk of work to switch to the scihub version.

**Comment by avalentino** [comment]
> Do you know of any reason not to use this one?

AFAIK http://aux.sentinel1.eo.esa.int does not have web API to make queries.

**Comment by system123** [comment]
I put together a simple script to download older orbit files from http://aux.sentinel1.eo.esa.int as not all of them are in the GNSS endpoint yet. Perhaps this is a quicker fix in the meantime, while we wait for the GNSS endpoint to become fully operational - so far ESA haven't been able to provide a roadmap for that.

https://gist.github.com/system123/3c2c3896c0d542999b15a02d19f82cb8

**Comment by avalentino** [comment]
Thanks a lot @tyler-c2s and @system123 for the additional Informational info and for the nice script.
Hope that the situation can improve quickly.

**Comment by espiritocz** [comment]
hi,

sorry again - i have switched to sentinelsat, using the orbits url. it was working ok but today we noticed there is a change and the sentinelsat output link shows not the new cloud web page, but instead it redirects to dhusfeed.dhus.onda-dias.net - and there i am failing to establish connection.

this is too unstable.
do you have any relevant news/updated eof?

**Comment by scottstanie** [comment]
No need to apologize, thanks for pointing it out (I haven't downloaded
orbits in awhile).
I'll take a look at cobbling together a way to try the official API, but
also trying the backup on failure. Should have time in the next few days

**Comment by espiritocz** [comment]
Thanks.

FYI, download from ASF works ok and seems keeping unchanging stability for
longterm use (but needs ASF credentials).

**Comment by avalentino** [comment]
Please see also https://github.com/johntruckenbrodt/pyroSAR/issues/141
I hope it is a temporary problem that can be fixed in the next few days.
Anyway, considering all the problems that we all are having with scihub in the last period, probably primary source for getting orbits should stay http://step.esa.int/auxdata/orbits.
Additional ones could be added as fallback.

@espiritocz can you please provide a link to orbit files on the ASF site?
The last time I checked the archive was not up to date but maybe I looked to the wrong place.

**Comment by espiritocz** [comment]
Sure!

ASF had also troubles in the time of the change to Copernicus Cloud if i
remember correctly.
But this seems fixed now.
I download just using
wget --user ... --password ... '
https://s1qc.asf.alaska.edu/aux_'$producttype'/'$filename
where i get the filename (S*.EOF) using the sentinelsat query to Copernicus
Cloud (discovery works normally).
producttype is either resorb or poeorb.

Hope it helps somehow

**Comment by avalentino** [comment]
Thanks @espiritocz.
Product listing is possible also without authentication: https://s1qc.asf.alaska.edu/aux_poeorb/
